# Generated by Django 5.2.1 on 2025-12-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('pppoe_user', models.CharField(max_length=50, unique=True)),
                ('pppoe_password', models.CharField(max_length=50)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Concentrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('api_user', models.CharField(max_length=50)),
                ('api_password', models.CharField(max_length=50)),
                ('api_port', models.IntegerField(default=8728)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ONT', 'Fibra Óptica (ONU)'), ('ROUTER', 'Roteador Wi-Fi')], max_length=10)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('ip_atual', models.GenericIPAddressField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('ultimo_sinal', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='devices.cliente')),
                ('concentrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.concentrador')),
            ],
        ),
    ]
