# Generated by Django 5.2.1 on 2025-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ramal', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('online', 'Disponível'), ('pausa', 'Pausa'), ('ocupado', 'Em Chamada'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('tempo_logado', models.DurationField(blank=True, help_text='Ex: 04:00:00', null=True)),
                ('atendimentos', models.IntegerField(default=0)),
            ],
        ),
    ]
