# Generated by Django 5.2.1 on 2025-12-09 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: U6-Pro', max_length=50)),
                ('localizacao', models.CharField(default='Setor A', help_text='Ex: Setor A-1', max_length=50)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('alerta', 'Alerta/Lento')], default='online', max_length=20)),
                ('usuarios_conectados', models.IntegerField(default=0)),
                ('cpu_usage', models.IntegerField(default=10, help_text='Uso em %')),
                ('memory_usage', models.IntegerField(default=30, help_text='Uso em %')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e Hora da medição')),
                ('chamadas_ativas', models.IntegerField(default=0)),
                ('trafego_rede_mbps', models.IntegerField(default=0, help_text='Uso em Mbps')),
            ],
            options={
                'verbose_name': 'Histórico de Operação',
                'verbose_name_plural': 'Histórico de Operações',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Brute Force, Port Scan', max_length=50)),
                ('origem', models.CharField(help_text='IP ou Usuário (Ex: 192.168.1.50)', max_length=50)),
                ('destino', models.CharField(default='Firewall', max_length=50)),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baixa', max_length=10)),
                ('status', models.BooleanField(default=False, verbose_name='Resolvido?')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ramal', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('online', 'Disponível'), ('pausa', 'Pausa'), ('ocupado', 'Em Chamada'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('tempo_logado', models.DurationField(blank=True, help_text='Ex: 04:00:00', null=True)),
                ('atendimentos', models.IntegerField(default=0)),
                ('departamento', models.CharField(choices=[('comercial', 'Comercial'), ('administrativo', 'Administrativo'), ('tecnico', 'Técnico')], default='tecnico', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('queda', 'Queda de Conexão'), ('lentidao', 'Internet Lenta'), ('wifi', 'Problema no Wi-Fi'), ('financeiro', 'Financeiro / Boleto'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('departamento', models.CharField(choices=[('comercial', 'Comercial'), ('administrativo', 'Administrativo'), ('tecnico', 'Técnico')], default='tecnico', max_length=20)),
                ('origem', models.CharField(choices=[('interno', 'Painel Interno'), ('whatsapp', 'WhatsApp Bot'), ('site', 'Widget do Site')], default='interno', max_length=10)),
                ('data_inicio_atendimento', models.DateTimeField(blank=True, help_text='Momento que o agente assumiu', null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='aberto', max_length=10)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('atribuido_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('cliente_isp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_isp', to='devices.cliente', verbose_name='Assinante Vinculado')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.chamado')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
