# Generated by Django 5.2.1 on 2025-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: U6-Pro-Setor-A', max_length=50)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('alerta', 'Alerta/Lento')], default='online', max_length=20)),
                ('usuarios_conectados', models.IntegerField(default=0)),
                ('cpu_usage', models.IntegerField(default=10, help_text='Uso em %')),
            ],
        ),
    ]
