# Generated by Django 5.2.1 on 2025-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='localizacao',
            field=models.CharField(default='Setor A', help_text='Ex: Setor A-1', max_length=50),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='memory_usage',
            field=models.IntegerField(default=30, help_text='Uso em %'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='nome',
            field=models.CharField(help_text='Ex: U6-Pro', max_length=50),
        ),
    ]
