# Generated by Django 5.2.1 on 2025-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesspoint_localizacao_accesspoint_memory_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Brute Force, Port Scan', max_length=50)),
                ('origem', models.CharField(help_text='IP ou Usuário (Ex: 192.168.1.50)', max_length=50)),
                ('destino', models.CharField(default='Firewall', max_length=50)),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baixa', max_length=10)),
                ('status', models.BooleanField(default=False, verbose_name='Resolvido?')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
