# Generated by Django 5.2.1 on 2025-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_securitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e Hora da medição')),
                ('chamadas_ativas', models.IntegerField(default=0)),
                ('trafego_rede_mbps', models.IntegerField(default=0, help_text='Uso em Mbps')),
            ],
            options={
                'verbose_name': 'Histórico de Operação',
                'verbose_name_plural': 'Histórico de Operações',
                'ordering': ['data_hora'],
            },
        ),
    ]
