# Generated by Django 5.2.9 on 2025-12-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_inicio_atendimento',
            field=models.DateTimeField(blank=True, help_text='Momento que o agente assumiu', null=True),
        ),
    ]
