# Generated by Django 5.2.9 on 2025-12-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chamado_data_inicio_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='departamento',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('administrativo', 'Administrativo'), ('tecnico', 'Técnico')], default='tecnico', max_length=20),
        ),
        migrations.AddField(
            model_name='chamado',
            name='departamento',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('administrativo', 'Administrativo'), ('tecnico', 'Técnico')], default='tecnico', max_length=20),
        ),
    ]
